services:
  - type: web
    name: mon-projet-php
    runtime: native
    plan: free  # Utilise "starter" ou "pro" si tu veux plus de ressources
    region: frankfurt  # Change selon ta localisation

    buildCommand: |
      composer install --no-dev --optimize-autoloader

    startCommand: |
      php -S 0.0.0.0:$PORT -t public  # Change "public" si ton projet n'a pas ce dossier

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true  # Génère automatiquement la clé Laravel si nécessaire
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: my-database-host
      - key: DB_DATABASE
        value: my-database-name
      - key: DB_USERNAME
        value: my-database-user
      - key: DB_PASSWORD
        value: my-database-password
