services:
  - type: web
    name: lbc
    plan: free  # Peut être "starter" ou "pro" si besoin
    region: frankfurt  # Changer si nécessaire
    dockerfilePath: ./Dockerfile  # On va créer un fichier Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: MAIL_HOST
        value: smtp.example.com  # Remplace par ton serveur SMTP
      - key: MAIL_USERNAME
        value: ton-email@example.com
      - key: MAIL_PASSWORD
        value: ton-mot-de-passe
      - key: MAIL_FROM
        value: ton-email@example.com
